/* ============================================================================
 * PWC 選手カード一覧（自動生成: tools/build_cards.js / 出典: data/pwc_cards.json）
 *  rar: '1' | '2' | '3' | '4' | '4F'(★4 FLOW) | '5'
 *  type: PWC のタイプ（キック / スピード / テクニック / 賢さ / フィジカル / スタミナ / コンディション）
 * ========================================================================== */
(function (root) {
  'use strict';
  var BL = root.BL = root.BL || {};
  BL.CARDS = [
  { id: 'c001', char: 'barou', title: "HUNTING BEAST", rar: '5', type: 'テクニック', pos: ["RWG","DMF"] },
  { id: 'c002', char: 'hiori', title: "「静」のテクニシャン", rar: '5', type: '賢さ', pos: ["RSB","RMF"] },
  { id: 'c003', char: 'isagi', title: "サッカー日本代表Ver.", rar: '5', type: '賢さ', pos: ["OMF","RSB"] },
  { id: 'c004', char: 'karasu', title: "広げる弱点と選択肢", rar: '5', type: 'テクニック', pos: ["DMF","OMF"] },
  { id: 'c005', char: 'nagi', title: "SUMMER SPLASH", rar: '5', type: 'キック', pos: ["OMF","CF"] },
  { id: 'c006', char: 'reo', title: "エレガント・ローズ", rar: '5', type: 'テクニック', pos: ["CB","DMF"] },
  { id: 'c007', char: 'rin', title: "夕紅色の風情", rar: '5', type: 'キック', pos: ["CF","LWG"] },
  { id: 'c008', char: 'sae', title: "夕紅色の風情", rar: '5', type: 'テクニック', pos: ["OMF","RMF"] },
  { id: 'c009', char: 'aiku', title: "捉える“間合い”", rar: '4F', type: '賢さ', pos: ["LSB","CB"] },
  { id: 'c010', char: 'bachira', title: "X 俺は俺のゴールのために", rar: '4F', type: 'テクニック', pos: ["LSB","RMF"] },
  { id: 'c011', char: 'chigiri', title: "縛られぬ速さ", rar: '4F', type: 'スピード', pos: ["RSB","LWG"] },
  { id: 'c012', char: 'otoya', title: "速攻の忍術", rar: '4F', type: 'スピード', pos: ["RMF","RWG"] },
  { id: 'c013', char: 'raichi', title: "噛み付くフィジカル", rar: '4F', type: 'フィジカル', pos: ["CB","DMF"] },
  { id: 'c014', char: 'sae', title: "次の景色を見せてやる", rar: '4F', type: 'テクニック', pos: ["LMF","OMF"] },
  { id: 'c015', char: 'sendou', title: "世界標準の欲望", rar: '4F', type: 'フィジカル', pos: ["CB","CF"] },
  { id: 'c016', char: 'shidou', title: "アンストッパブル・デーモン", rar: '4F', type: 'キック', pos: ["RWG","CF"] },
  { id: 'c017', char: 'aiku', title: "オールMAXで視える世界", rar: '4', type: 'フィジカル', pos: ["CB","DMF"] },
  { id: 'c018', char: 'bachira', title: "怪物夢中", rar: '4', type: 'テクニック', pos: ["LSB","LMF"] },
  { id: 'c019', char: 'barou', title: "貪り喰らう咆哮", rar: '4', type: 'キック', pos: ["OMF","RWG"] },
  { id: 'c020', char: 'chigiri', title: "ブリリアント・ブーケ", rar: '4', type: '賢さ', pos: ["RSB","RMF"] },
  { id: 'c021', char: 'chigiri', title: "最速の韋駄天", rar: '4', type: 'スピード', pos: ["RSB","RMF"] },
  { id: 'c022', char: 'hiori', title: "X 自分にできる武器", rar: '4', type: '賢さ', pos: ["RSB","LSB"] },
  { id: 'c023', char: 'isagi', title: "”青い監獄”の心臓", rar: '4', type: '賢さ', pos: ["LMF","OMF"] },
  { id: 'c024', char: 'isagi', title: "3周年記念Ver.", rar: '4', type: '賢さ', pos: ["LSB","OMF"] },
  { id: 'c025', char: 'karasu', title: "X 弱点がないなら創るまで", rar: '4', type: 'テクニック', pos: ["RMF","DMF"] },
  { id: 'c026', char: 'kunigami', title: "正々堂々肉体勝負", rar: '4', type: 'フィジカル', pos: ["LSB","CF"] },
  { id: 'c027', char: 'kurona', title: "小柄なシャーク", rar: '4', type: 'テクニック', pos: ["RSB","DMF"] },
  { id: 'c028', char: 'mitoma', title: "受け止めた勝利", rar: '4', type: 'フィジカル', pos: ["CB","OMF"] },
  { id: 'c029', char: 'nagi', title: "3周年記念Ver.", rar: '4', type: 'スピード', pos: ["RMF","OMF"] },
  { id: 'c030', char: 'nagi', title: "はじめまして日本", rar: '4', type: 'キック', pos: ["OMF","LWG"] },
  { id: 'c031', char: 'nanase', title: "X トレッキング・トレーニング", rar: '4', type: 'テクニック', pos: ["RMF","LMF"] },
  { id: 'c032', char: 'reo', title: "X SEASIDE EGOIST", rar: '4', type: 'テクニック', pos: ["CB","DMF"] },
  { id: 'c033', char: 'reo', title: "万能のカメレオン", rar: '4', type: 'フィジカル', pos: ["RSB","CB"] },
  { id: 'c034', char: 'rin', title: "SEASIDE EGOIST", rar: '4', type: 'キック', pos: ["RWG","CF"] },
  { id: 'c035', char: 'rin', title: "X 相性最悪のクリスマス", rar: '4', type: 'テクニック', pos: ["DMF","CF"] },
  { id: 'c036', char: 'rin', title: "破壊者", rar: '4', type: 'スピード', pos: ["LWG","CF"] },
  { id: 'c037', char: 'sae', title: "『美しく壊す』哲学", rar: '4', type: 'テクニック', pos: ["LMF","OMF"] },
  { id: 'c038', char: 'sae', title: "SEASIDE EGOIST", rar: '4', type: 'スピード', pos: ["LMF","OMF"] },
  { id: 'c039', char: 'shidou', title: "歓喜の”誕生”", rar: '4', type: 'キック', pos: ["LWG","CF"] },
  { id: 'c040', char: 'yukimiya', title: "一瞬に見出す極限", rar: '4', type: 'スピード', pos: ["LMF","LWG"] },
  { id: 'c041', char: 'aiku', title: "U-20日本代表主将", rar: '3', type: 'フィジカル', pos: ["LSB"] },
  { id: 'c042', char: 'aryu', title: "No.1オシャ", rar: '3', type: 'テクニック', pos: ["OMF"] },
  { id: 'c043', char: 'aryu', title: "反則級の特級身体", rar: '3', type: 'フィジカル', pos: ["CB"] },
  { id: 'c044', char: 'bachira', title: "X 呪縛からの解放", rar: '3', type: 'テクニック', pos: ["OMF"] },
  { id: 'c045', char: 'bachira', title: "かいぶつのいない世界", rar: '3', type: '賢さ', pos: ["RMF"] },
  { id: 'c046', char: 'bachira', title: "正面突破", rar: '3', type: 'テクニック', pos: ["DMF"] },
  { id: 'c047', char: 'bachira', title: "変幻自在の足技", rar: '3', type: 'テクニック', pos: ["RMF"] },
  { id: 'c048', char: 'bachira', title: "遊興の法被姿", rar: '3', type: 'テクニック', pos: ["RMF"] },
  { id: 'c049', char: 'barou', title: "HUNGER WOLF", rar: '3', type: 'テクニック', pos: ["OMF"] },
  { id: 'c050', char: 'barou', title: "俺が王様だ", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c051', char: 'barou', title: "混乱を創る独裁の王", rar: '3', type: 'スピード', pos: ["RWG"] },
  { id: 'c052', char: 'barou', title: "邪道こそが王道", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c053', char: 'blake', title: "GGジャンキー", rar: '3', type: 'フィジカル', pos: ["DMF"] },
  { id: 'c054', char: 'cavazos', title: "そばかすベイビー", rar: '3', type: 'テクニック', pos: ["DMF"] },
  { id: 'c055', char: 'chigiri', title: "X この熱が尽きるまで", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c056', char: 'chigiri', title: "最速の蹴撃", rar: '3', type: 'スピード', pos: ["RWG"] },
  { id: 'c057', char: 'chigiri', title: "聖夜の赤豹", rar: '3', type: 'スピード', pos: ["RWG"] },
  { id: 'c058', char: 'chigiri', title: "熱い滾り", rar: '3', type: 'スピード', pos: ["RWG"] },
  { id: 'c059', char: 'chigiri', title: "浴衣姿の趣", rar: '3', type: 'スピード', pos: ["LMF"] },
  { id: 'c060', char: 'dada', title: "重戦車", rar: '3', type: 'スタミナ', pos: ["LSB"] },
  { id: 'c061', char: 'gagamaru', title: "アクロバティック", rar: '3', type: 'フィジカル', pos: ["CB"] },
  { id: 'c062', char: 'gagamaru', title: "野生児", rar: '3', type: 'スピード', pos: ["RMF"] },
  { id: 'c063', char: 'hiori', title: "はんなりゲーマー", rar: '3', type: '賢さ', pos: ["LSB"] },
  { id: 'c064', char: 'hiori', title: "桜はんなり", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c065', char: 'hiori', title: "冷静な視野", rar: '3', type: 'スピード', pos: ["LWG"] },
  { id: 'c066', char: 'honda', title: "永遠の挑戦者", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c067', char: 'igarashi', title: "駆け上がる渇望", rar: '3', type: 'コンディション', pos: ["DMF"] },
  { id: 'c068', char: 'igarashi', title: "諦めない心", rar: '3', type: 'コンディション', pos: ["DMF"] },
  { id: 'c069', char: 'isagi', title: "この一瞬に『反射』しろ", rar: '3', type: 'テクニック', pos: ["DMF"] },
  { id: 'c070', char: 'isagi', title: "ストライカー", rar: '3', type: '賢さ', pos: ["LSB"] },
  { id: 'c071', char: 'isagi', title: "運命への第一歩", rar: '3', type: 'スタミナ', pos: ["CF"] },
  { id: 'c072', char: 'isagi', title: "主役の座", rar: '3', type: '賢さ', pos: ["RMF"] },
  { id: 'c073', char: 'isagi', title: "進化する視野", rar: '3', type: '賢さ', pos: ["RSB"] },
  { id: 'c074', char: 'isagi', title: "戦場の桜花", rar: '3', type: '賢さ', pos: ["RSB"] },
  { id: 'c075', char: 'karasu', title: "ヒットマン", rar: '3', type: 'テクニック', pos: ["DMF"] },
  { id: 'c076', char: 'karasu', title: "無欠への一手", rar: '3', type: '賢さ', pos: ["RSB"] },
  { id: 'c077', char: 'kira', title: "みんなに届ける恩返し", rar: '3', type: 'スタミナ', pos: ["LSB"] },
  { id: 'c078', char: 'kira', title: "松風黒王のエース", rar: '3', type: 'スピード', pos: ["LWG"] },
  { id: 'c079', char: 'kiyora', title: "ボーダーライナー", rar: '3', type: '賢さ', pos: ["LSB"] },
  { id: 'c080', char: 'kunigami', title: "ジューンブライド・ヒーロー", rar: '3', type: 'フィジカル', pos: ["CB"] },
  { id: 'c081', char: 'kunigami', title: "驚異の左足", rar: '3', type: 'フィジカル', pos: ["RSB"] },
  { id: 'c082', char: 'kunigami', title: "空中の肉弾戦", rar: '3', type: 'フィジカル', pos: ["RSB"] },
  { id: 'c083', char: 'kunigami', title: "全身全霊の一閃", rar: '3', type: 'フィジカル', pos: ["CB"] },
  { id: 'c084', char: 'loki', title: "神童", rar: '3', type: 'スピード', pos: ["RWG"] },
  { id: 'c085', char: 'luna', title: "レ・アールの貴公子", rar: '3', type: 'テクニック', pos: ["OMF"] },
  { id: 'c086', char: 'mitoma', title: "勝利への執念", rar: '3', type: 'スピード', pos: ["LWG"] },
  { id: 'c087', char: 'mitoma', title: "信念を貫くドリブル", rar: '3', type: 'キック', pos: ["RWG"] },
  { id: 'c088', char: 'mitoma', title: "電光石火", rar: '3', type: 'テクニック', pos: ["DMF"] },
  { id: 'c089', char: 'mitoma', title: "独走のワールドストライカー", rar: '3', type: '賢さ', pos: ["RSB"] },
  { id: 'c090', char: 'nagi', title: "1周年記念Ver.", rar: '3', type: 'テクニック', pos: ["LMF"] },
  { id: 'c091', char: 'nagi', title: "X 反転蹴弾", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c092', char: 'nagi', title: "X’mas", rar: '3', type: '賢さ', pos: ["LMF"] },
  { id: 'c093', char: 'nagi', title: "好奇心という名の衝動", rar: '3', type: 'テクニック', pos: ["OMF"] },
  { id: 'c094', char: 'nagi', title: "変幻自在のトラップ", rar: '3', type: 'キック', pos: ["OMF"] },
  { id: 'c095', char: 'nagi', title: "浴衣姿の趣", rar: '3', type: 'テクニック', pos: ["DMF"] },
  { id: 'c096', char: 'nanase', title: "天然記念物", rar: '3', type: 'スピード', pos: ["RWG"] },
  { id: 'c097', char: 'niko', title: "影の支配者", rar: '3', type: '賢さ', pos: ["RSB"] },
  { id: 'c098', char: 'niko', title: "無限の発想", rar: '3', type: '賢さ', pos: ["LMF"] },
  { id: 'c099', char: 'otoya', title: "最強の飛び道具", rar: '3', type: 'テクニック', pos: ["LMF"] },
  { id: 'c100', char: 'otoya', title: "忍者の末裔", rar: '3', type: 'スピード', pos: ["RWG"] },
  { id: 'c101', char: 'raichi', title: "起死回生の一蹴", rar: '3', type: 'フィジカル', pos: ["RSB"] },
  { id: 'c102', char: 'raichi', title: "執念の男", rar: '3', type: 'スタミナ', pos: ["CB"] },
  { id: 'c103', char: 'raichi', title: "傍若無人強奪", rar: '3', type: 'フィジカル', pos: ["CB"] },
  { id: 'c104', char: 'reo', title: "1周年記念Ver.", rar: '3', type: 'テクニック', pos: ["DMF"] },
  { id: 'c105', char: 'reo', title: "Present to You", rar: '3', type: '賢さ', pos: ["LMF"] },
  { id: 'c106', char: 'reo', title: "X 狙撃手パス", rar: '3', type: 'スピード', pos: ["LWG"] },
  { id: 'c107', char: 'reo', title: "再現する才能", rar: '3', type: '賢さ', pos: ["LMF"] },
  { id: 'c108', char: 'reo', title: "自負と決意の『複写』", rar: '3', type: 'スタミナ', pos: ["CB"] },
  { id: 'c109', char: 'reo', title: "絶対勝つ", rar: '3', type: 'テクニック', pos: ["LMF"] },
  { id: 'c110', char: 'rin', title: "1周年記念Ver.", rar: '3', type: '賢さ', pos: ["LSB"] },
  { id: 'c111', char: 'rin', title: "一瞬に懸ける命", rar: '3', type: '賢さ', pos: ["LSB"] },
  { id: 'c112', char: 'rin', title: "蹴り描く放物線", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c113', char: 'rin', title: "戦場の支配者", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c114', char: 'sendou', title: "U-20日本代表エース", rar: '3', type: 'キック', pos: ["OMF"] },
  { id: 'c115', char: 'sendou', title: "エースの意地", rar: '3', type: 'スピード', pos: ["LWG"] },
  { id: 'c116', char: 'shidou', title: "Halloween Demon", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c117', char: 'shidou', title: "PA最強の悪魔", rar: '3', type: 'キック', pos: ["LWG"] },
  { id: 'c118', char: 'shidou', title: "超弩級の個人能力", rar: '3', type: 'キック', pos: ["RWG"] },
  { id: 'c119', char: 'shidou', title: "龍聖・直下蹴弾", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c120', char: 'tokimitsu', title: "X 背肩奪取", rar: '3', type: 'フィジカル', pos: ["CB"] },
  { id: 'c121', char: 'tokimitsu', title: "フィジカルモンスター", rar: '3', type: 'スタミナ', pos: ["CB"] },
  { id: 'c122', char: 'yukimiya', title: "1on1エンペラー", rar: '3', type: 'キック', pos: ["OMF"] },
  { id: 'c123', char: 'yukimiya', title: "ストリート・スタイル", rar: '3', type: 'キック', pos: ["CF"] },
  { id: 'c124', char: 'zantetsu', title: "俺の”領域”", rar: '3', type: 'スピード', pos: ["RMF"] },
  { id: 'c125', char: 'zantetsu', title: "名誉返上の守備", rar: '3', type: 'スピード', pos: ["LMF"] },
  { id: 'c126', char: 'aryu', title: "新ＢＬランキング2位", rar: '2', type: 'フィジカル', pos: ["LSB"] },
  { id: 'c127', char: 'bachira', title: "ドリブラー", rar: '2', type: 'テクニック', pos: ["DMF"] },
  { id: 'c128', char: 'barou', title: "強烈な個性", rar: '2', type: 'キック', pos: ["OMF"] },
  { id: 'c129', char: 'blake', title: "イングランド代表", rar: '2', type: 'フィジカル', pos: ["CB"] },
  { id: 'c130', char: 'cavazos', title: "アルゼンチン代表", rar: '2', type: 'テクニック', pos: ["OMF"] },
  { id: 'c131', char: 'chigiri', title: "スピードスター", rar: '2', type: 'スピード', pos: ["LWG"] },
  { id: 'c132', char: 'dada', title: "ブラジル代表", rar: '2', type: 'スタミナ', pos: ["CB"] },
  { id: 'c133', char: 'gagamaru', title: "肉体のバネ", rar: '2', type: 'フィジカル', pos: ["RSB"] },
  { id: 'c134', char: 'iemon', title: "鉄壁", rar: '2', type: 'コンディション', pos: ["DMF"] },
  { id: 'c135', char: 'igarashi', title: "南無三", rar: '2', type: 'コンディション', pos: ["RWG"] },
  { id: 'c136', char: 'imamura', title: "恋愛脳", rar: '2', type: 'テクニック', pos: ["DMF"] },
  { id: 'c137', char: 'isagi', title: "空間認識能力の萌芽", rar: '2', type: '賢さ', pos: ["RSB"] },
  { id: 'c138', char: 'kira', title: "日本サッカー界の宝", rar: '2', type: 'スピード', pos: ["RWG"] },
  { id: 'c139', char: 'kunigami', title: "スーパーヒーローの卵", rar: '2', type: 'キック', pos: ["CF"] },
  { id: 'c140', char: 'kuon', title: "ハイジャンパー", rar: '2', type: 'フィジカル', pos: ["CB"] },
  { id: 'c141', char: 'loki', title: "フランス代表", rar: '2', type: 'スピード', pos: ["LWG"] },
  { id: 'c142', char: 'luna', title: "スペイン代表", rar: '2', type: 'テクニック', pos: ["RMF"] },
  { id: 'c143', char: 'nagi', title: "異次元の発想", rar: '2', type: 'テクニック', pos: ["RMF"] },
  { id: 'c144', char: 'naruhaya', title: "ムードメーカー", rar: '2', type: '賢さ', pos: ["RSB"] },
  { id: 'c145', char: 'niko', title: "チームＹの心臓", rar: '2', type: '賢さ', pos: ["LMF"] },
  { id: 'c146', char: 'okawa', title: "熊本県大会得点王", rar: '2', type: 'コンディション', pos: ["CF"] },
  { id: 'c147', char: 'raichi', title: "スタミナの塊", rar: '2', type: 'スタミナ', pos: ["RWG"] },
  { id: 'c148', char: 'reo', title: "御曹司", rar: '2', type: '賢さ', pos: ["RMF"] },
  { id: 'c149', char: 'rin', title: "新BLランキング1位", rar: '2', type: '賢さ', pos: ["RSB"] },
  { id: 'c150', char: 'shidou', title: "生命の爆発", rar: '2', type: 'キック', pos: ["CF"] },
  { id: 'c151', char: 'tokimitsu', title: "新BLランキング3位", rar: '2', type: 'スタミナ', pos: ["DMF"] },
  { id: 'c152', char: 'wanima_j', title: "弟との以心伝心連携", rar: '2', type: 'キック', pos: ["LWG"] },
  { id: 'c153', char: 'wanima_k', title: "兄との以心伝心連携", rar: '2', type: 'テクニック', pos: ["OMF"] },
  { id: 'c154', char: 'zantetsu', title: "独特な語彙力", rar: '2', type: 'スピード', pos: ["LWG"] },
  { id: 'c155', char: 'bachira', title: "チームＺ", rar: '1', type: 'テクニック', pos: ["OMF"] },
  { id: 'c156', char: 'chigiri', title: "チームＺ", rar: '1', type: 'スピード', pos: ["RWG"] },
  { id: 'c157', char: 'gagamaru', title: "チームＺ", rar: '1', type: 'フィジカル', pos: ["CB"] },
  { id: 'c158', char: 'iemon', title: "チームＺ", rar: '1', type: 'コンディション', pos: ["LWG"] },
  { id: 'c159', char: 'igarashi', title: "チームＺ", rar: '1', type: 'コンディション', pos: ["LWG"] },
  { id: 'c160', char: 'imamura', title: "チームＺ", rar: '1', type: 'テクニック', pos: ["OMF"] },
  { id: 'c161', char: 'isagi', title: "チームＺ", rar: '1', type: 'キック', pos: ["OMF"] },
  { id: 'c162', char: 'kira', title: "チームＺ", rar: '1', type: 'コンディション', pos: ["RMF"] },
  { id: 'c163', char: 'kunigami', title: "チームＺ", rar: '1', type: 'フィジカル', pos: ["CB"] },
  { id: 'c164', char: 'kuon', title: "チームＺ", rar: '1', type: 'フィジカル', pos: ["LSB"] },
  { id: 'c165', char: 'naruhaya', title: "チームＺ", rar: '1', type: 'スピード', pos: ["RMF"] },
  { id: 'c166', char: 'niko', title: "チームＹ", rar: '1', type: '賢さ', pos: ["LSB"] },
  { id: 'c167', char: 'okawa', title: "チームＹ", rar: '1', type: 'フィジカル', pos: ["CB"] },
  { id: 'c168', char: 'raichi', title: "チームＺ", rar: '1', type: 'スタミナ', pos: ["CF"] },
  { id: 'c169', char: 'wanima_j', title: "チームＷ", rar: '1', type: '賢さ', pos: ["LSB"] },
  { id: 'c170', char: 'wanima_k', title: "チームＷ", rar: '1', type: 'テクニック', pos: ["LMF"] }
  ];
})(typeof globalThis !== 'undefined' ? globalThis : this);
