/* ============================================================================
 * 選手カード一覧（自動生成: tools/build_cards.js / 出典: data/pwc_cards.json + 改変版オリジナル）
 *  rar: '1'〜'8'（8段階） flow: ★4FLOW 由来  pwc: PWC でのレアリティ（null = 改変版オリジナル）
 *  type: PWC のタイプ（キック / スピード / テクニック / 賢さ / フィジカル / スタミナ / コンディション）
 * ========================================================================== */
(function (root) {
  'use strict';
  var BL = root.BL = root.BL || {};
  BL.CARDS = [
  { id: 'k001', char: 'ego_if', title: "現役if・青い監獄の設計者", rar: '8', flow: false, pwc: null, origin: 'mod', type: '賢さ', pos: ["OMF","DMF"] },
  { id: 'k002', char: 'noa', title: "世界最高のストライカー", rar: '8', flow: false, pwc: null, origin: 'mod', type: 'キック', pos: ["CF","OMF"] },
  { id: 'k003', char: 'isagi', title: "サッカー日本代表Ver.", rar: '7', flow: false, pwc: "5", origin: 'pwc', type: '賢さ', pos: ["OMF","RSB"] },
  { id: 'k004', char: 'lavinho', title: "マスター・FCバルチャ", rar: '7', flow: false, pwc: null, origin: 'mod', type: 'テクニック', pos: ["LWG","OMF"] },
  { id: 'k005', char: 'loki', title: "フランス代表", rar: '7', flow: false, pwc: "2", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k006', char: 'loki', title: "神童", rar: '7', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k007', char: 'mitoma', title: "受け止めた勝利", rar: '7', flow: false, pwc: "4", origin: 'pwc', type: 'フィジカル', pos: ["CB","OMF"] },
  { id: 'k008', char: 'prince', title: "マスター・マンシャイン", rar: '7', flow: false, pwc: null, origin: 'mod', type: 'キック', pos: ["CF","RWG"] },
  { id: 'k009', char: 'rin', title: "夕紅色の風情", rar: '7', flow: false, pwc: "5", origin: 'pwc', type: 'キック', pos: ["CF","LWG"] },
  { id: 'k010', char: 'sae', title: "『美しく壊す』哲学", rar: '7', flow: false, pwc: "4", origin: 'pwc', type: 'テクニック', pos: ["LMF","OMF"] },
  { id: 'k011', char: 'sae', title: "SEASIDE EGOIST", rar: '7', flow: false, pwc: "4", origin: 'pwc', type: 'スピード', pos: ["LMF","OMF"] },
  { id: 'k012', char: 'sae', title: "次の景色を見せてやる", rar: '7', flow: true, pwc: "4FLOW", origin: 'pwc', type: 'テクニック', pos: ["LMF","OMF"] },
  { id: 'k013', char: 'sae', title: "夕紅色の風情", rar: '7', flow: false, pwc: "5", origin: 'pwc', type: 'テクニック', pos: ["OMF","RMF"] },
  { id: 'k014', char: 'snuffy', title: "マスター・ユーヴァース", rar: '7', flow: false, pwc: null, origin: 'mod', type: '賢さ', pos: ["DMF","CB"] },
  { id: 'k015', char: 'aiku', title: "オールMAXで視える世界", rar: '6', flow: false, pwc: "4", origin: 'pwc', type: 'フィジカル', pos: ["CB","DMF"] },
  { id: 'k016', char: 'aiku', title: "捉える“間合い”", rar: '6', flow: true, pwc: "4FLOW", origin: 'pwc', type: '賢さ', pos: ["LSB","CB"] },
  { id: 'k017', char: 'barou', title: "HUNTING BEAST", rar: '6', flow: false, pwc: "5", origin: 'pwc', type: 'テクニック', pos: ["RWG","DMF"] },
  { id: 'k018', char: 'blake', title: "GGジャンキー", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["DMF"] },
  { id: 'k019', char: 'blake', title: "イングランド代表", rar: '6', flow: false, pwc: "2", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k020', char: 'cavazos', title: "アルゼンチン代表", rar: '6', flow: false, pwc: "2", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k021', char: 'cavazos', title: "そばかすベイビー", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k022', char: 'chevalier', title: "電光石火の騎士", rar: '6', flow: false, pwc: null, origin: 'mod', type: 'スピード', pos: ["RWG","CF"] },
  { id: 'k023', char: 'dada', title: "ブラジル代表", rar: '6', flow: false, pwc: "2", origin: 'pwc', type: 'スタミナ', pos: ["CB"] },
  { id: 'k024', char: 'dada', title: "重戦車", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'スタミナ', pos: ["LSB"] },
  { id: 'k025', char: 'hiori', title: "「静」のテクニシャン", rar: '6', flow: false, pwc: "5", origin: 'pwc', type: '賢さ', pos: ["RSB","RMF"] },
  { id: 'k026', char: 'honda', title: "永遠の挑戦者", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k027', char: 'isagi', title: "”青い監獄”の心臓", rar: '6', flow: false, pwc: "4", origin: 'pwc', type: '賢さ', pos: ["LMF","OMF"] },
  { id: 'k028', char: 'isagi', title: "3周年記念Ver.", rar: '6', flow: false, pwc: "4", origin: 'pwc', type: '賢さ', pos: ["LSB","OMF"] },
  { id: 'k029', char: 'kaiser', title: "皇帝", rar: '6', flow: false, pwc: null, origin: 'mod', type: 'キック', pos: ["CF","LWG"] },
  { id: 'k030', char: 'karasu', title: "広げる弱点と選択肢", rar: '6', flow: false, pwc: "5", origin: 'pwc', type: 'テクニック', pos: ["DMF","OMF"] },
  { id: 'k031', char: 'lorenzo', title: "守備の魔物", rar: '6', flow: false, pwc: null, origin: 'mod', type: 'フィジカル', pos: ["CB","DMF"] },
  { id: 'k032', char: 'luna', title: "スペイン代表", rar: '6', flow: false, pwc: "2", origin: 'pwc', type: 'テクニック', pos: ["RMF"] },
  { id: 'k033', char: 'luna', title: "レ・アールの貴公子", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k034', char: 'mitoma', title: "勝利への執念", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k035', char: 'mitoma', title: "信念を貫くドリブル", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["RWG"] },
  { id: 'k036', char: 'mitoma', title: "電光石火", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k037', char: 'mitoma', title: "独走のワールドストライカー", rar: '6', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k038', char: 'nagi', title: "SUMMER SPLASH", rar: '6', flow: false, pwc: "5", origin: 'pwc', type: 'キック', pos: ["OMF","CF"] },
  { id: 'k039', char: 'reo', title: "エレガント・ローズ", rar: '6', flow: false, pwc: "5", origin: 'pwc', type: 'テクニック', pos: ["CB","DMF"] },
  { id: 'k040', char: 'rin', title: "SEASIDE EGOIST", rar: '6', flow: false, pwc: "4", origin: 'pwc', type: 'キック', pos: ["RWG","CF"] },
  { id: 'k041', char: 'rin', title: "X 相性最悪のクリスマス", rar: '6', flow: false, pwc: "4", origin: 'pwc', type: 'テクニック', pos: ["DMF","CF"] },
  { id: 'k042', char: 'rin', title: "破壊者", rar: '6', flow: false, pwc: "4", origin: 'pwc', type: 'スピード', pos: ["LWG","CF"] },
  { id: 'k043', char: 'sendou', title: "世界標準の欲望", rar: '6', flow: true, pwc: "4FLOW", origin: 'pwc', type: 'フィジカル', pos: ["CB","CF"] },
  { id: 'k044', char: 'shidou', title: "アンストッパブル・デーモン", rar: '6', flow: true, pwc: "4FLOW", origin: 'pwc', type: 'キック', pos: ["RWG","CF"] },
  { id: 'k045', char: 'shidou', title: "歓喜の”誕生”", rar: '6', flow: false, pwc: "4", origin: 'pwc', type: 'キック', pos: ["LWG","CF"] },
  { id: 'k046', char: 'aiku', title: "U-20日本代表主将", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["LSB"] },
  { id: 'k047', char: 'bachira', title: "X 俺は俺のゴールのために", rar: '5', flow: true, pwc: "4FLOW", origin: 'pwc', type: 'テクニック', pos: ["LSB","RMF"] },
  { id: 'k048', char: 'bachira', title: "怪物夢中", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'テクニック', pos: ["LSB","LMF"] },
  { id: 'k049', char: 'barou', title: "貪り喰らう咆哮", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'キック', pos: ["OMF","RWG"] },
  { id: 'k050', char: 'chigiri', title: "ブリリアント・ブーケ", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: '賢さ', pos: ["RSB","RMF"] },
  { id: 'k051', char: 'chigiri', title: "最速の韋駄天", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'スピード', pos: ["RSB","RMF"] },
  { id: 'k052', char: 'chigiri', title: "縛られぬ速さ", rar: '5', flow: true, pwc: "4FLOW", origin: 'pwc', type: 'スピード', pos: ["RSB","LWG"] },
  { id: 'k053', char: 'hiori', title: "X 自分にできる武器", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: '賢さ', pos: ["RSB","LSB"] },
  { id: 'k054', char: 'hiori', title: "はんなりゲーマー", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LSB"] },
  { id: 'k055', char: 'hiori', title: "桜はんなり", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k056', char: 'hiori', title: "冷静な視野", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k057', char: 'karasu', title: "X 弱点がないなら創るまで", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'テクニック', pos: ["RMF","DMF"] },
  { id: 'k058', char: 'karasu', title: "ヒットマン", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k059', char: 'karasu', title: "無欠への一手", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k060', char: 'kunigami', title: "正々堂々肉体勝負", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'フィジカル', pos: ["LSB","CF"] },
  { id: 'k061', char: 'kurona', title: "小柄なシャーク", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'テクニック', pos: ["RSB","DMF"] },
  { id: 'k062', char: 'nagi', title: "3周年記念Ver.", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'スピード', pos: ["RMF","OMF"] },
  { id: 'k063', char: 'nagi', title: "はじめまして日本", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'キック', pos: ["OMF","LWG"] },
  { id: 'k064', char: 'nanase', title: "X トレッキング・トレーニング", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'テクニック', pos: ["RMF","LMF"] },
  { id: 'k065', char: 'ness', title: "皇帝の魔術師", rar: '5', flow: false, pwc: null, origin: 'mod', type: 'テクニック', pos: ["OMF","LMF"] },
  { id: 'k066', char: 'otoya', title: "最強の飛び道具", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["LMF"] },
  { id: 'k067', char: 'otoya', title: "速攻の忍術", rar: '5', flow: true, pwc: "4FLOW", origin: 'pwc', type: 'スピード', pos: ["RMF","RWG"] },
  { id: 'k068', char: 'otoya', title: "忍者の末裔", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k069', char: 'reo', title: "X SEASIDE EGOIST", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'テクニック', pos: ["CB","DMF"] },
  { id: 'k070', char: 'reo', title: "万能のカメレオン", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'フィジカル', pos: ["RSB","CB"] },
  { id: 'k071', char: 'rin', title: "1周年記念Ver.", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LSB"] },
  { id: 'k072', char: 'rin', title: "一瞬に懸ける命", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LSB"] },
  { id: 'k073', char: 'rin', title: "蹴り描く放物線", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k074', char: 'rin', title: "戦場の支配者", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k075', char: 'sendou', title: "U-20日本代表エース", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["OMF"] },
  { id: 'k076', char: 'sendou', title: "エースの意地", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k077', char: 'shidou', title: "Halloween Demon", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k078', char: 'shidou', title: "PA最強の悪魔", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["LWG"] },
  { id: 'k079', char: 'shidou', title: "超弩級の個人能力", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["RWG"] },
  { id: 'k080', char: 'shidou', title: "龍聖・直下蹴弾", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k081', char: 'yukimiya', title: "1on1エンペラー", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["OMF"] },
  { id: 'k082', char: 'yukimiya', title: "ストリート・スタイル", rar: '5', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k083', char: 'yukimiya', title: "一瞬に見出す極限", rar: '5', flow: false, pwc: "4", origin: 'pwc', type: 'スピード', pos: ["LMF","LWG"] },
  { id: 'k084', char: 'aryu', title: "No.1オシャ", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k085', char: 'aryu', title: "反則級の特級身体", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k086', char: 'bachira', title: "X 呪縛からの解放", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k087', char: 'bachira', title: "かいぶつのいない世界", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["RMF"] },
  { id: 'k088', char: 'bachira', title: "正面突破", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k089', char: 'bachira', title: "変幻自在の足技", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["RMF"] },
  { id: 'k090', char: 'bachira', title: "遊興の法被姿", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["RMF"] },
  { id: 'k091', char: 'barou', title: "HUNGER WOLF", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k092', char: 'barou', title: "俺が王様だ", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k093', char: 'barou', title: "混乱を創る独裁の王", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k094', char: 'barou', title: "邪道こそが王道", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k095', char: 'chigiri', title: "X この熱が尽きるまで", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k096', char: 'chigiri', title: "最速の蹴撃", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k097', char: 'chigiri', title: "聖夜の赤豹", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k098', char: 'chigiri', title: "熱い滾り", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k099', char: 'chigiri', title: "浴衣姿の趣", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["LMF"] },
  { id: 'k100', char: 'isagi', title: "この一瞬に『反射』しろ", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k101', char: 'isagi', title: "ストライカー", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LSB"] },
  { id: 'k102', char: 'isagi', title: "運命への第一歩", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スタミナ', pos: ["CF"] },
  { id: 'k103', char: 'isagi', title: "主役の座", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["RMF"] },
  { id: 'k104', char: 'isagi', title: "進化する視野", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k105', char: 'isagi', title: "戦場の桜花", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k106', char: 'kiyora', title: "ボーダーライナー", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LSB"] },
  { id: 'k107', char: 'kunigami', title: "ジューンブライド・ヒーロー", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k108', char: 'kunigami', title: "驚異の左足", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["RSB"] },
  { id: 'k109', char: 'kunigami', title: "空中の肉弾戦", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["RSB"] },
  { id: 'k110', char: 'kunigami', title: "全身全霊の一閃", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k111', char: 'nagi', title: "1周年記念Ver.", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["LMF"] },
  { id: 'k112', char: 'nagi', title: "X 反転蹴弾", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k113', char: 'nagi', title: "X’mas", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LMF"] },
  { id: 'k114', char: 'nagi', title: "好奇心という名の衝動", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k115', char: 'nagi', title: "変幻自在のトラップ", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'キック', pos: ["OMF"] },
  { id: 'k116', char: 'nagi', title: "浴衣姿の趣", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k117', char: 'nanase', title: "天然記念物", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k118', char: 'raichi', title: "噛み付くフィジカル", rar: '4', flow: true, pwc: "4FLOW", origin: 'pwc', type: 'フィジカル', pos: ["CB","DMF"] },
  { id: 'k119', char: 'reo', title: "1周年記念Ver.", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k120', char: 'reo', title: "Present to You", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LMF"] },
  { id: 'k121', char: 'reo', title: "X 狙撃手パス", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k122', char: 'reo', title: "再現する才能", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LMF"] },
  { id: 'k123', char: 'reo', title: "自負と決意の『複写』", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スタミナ', pos: ["CB"] },
  { id: 'k124', char: 'reo', title: "絶対勝つ", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'テクニック', pos: ["LMF"] },
  { id: 'k125', char: 'rin', title: "新BLランキング1位", rar: '4', flow: false, pwc: "2", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k126', char: 'shidou', title: "生命の爆発", rar: '4', flow: false, pwc: "2", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k127', char: 'tokimitsu', title: "X 背肩奪取", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k128', char: 'tokimitsu', title: "フィジカルモンスター", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スタミナ', pos: ["CB"] },
  { id: 'k129', char: 'zantetsu', title: "俺の”領域”", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RMF"] },
  { id: 'k130', char: 'zantetsu', title: "名誉返上の守備", rar: '4', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["LMF"] },
  { id: 'k131', char: 'aryu', title: "新ＢＬランキング2位", rar: '3', flow: false, pwc: "2", origin: 'pwc', type: 'フィジカル', pos: ["LSB"] },
  { id: 'k132', char: 'barou', title: "強烈な個性", rar: '3', flow: false, pwc: "2", origin: 'pwc', type: 'キック', pos: ["OMF"] },
  { id: 'k133', char: 'gagamaru', title: "アクロバティック", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k134', char: 'gagamaru', title: "野生児", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["RMF"] },
  { id: 'k135', char: 'igarashi', title: "駆け上がる渇望", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'コンディション', pos: ["DMF"] },
  { id: 'k136', char: 'igarashi', title: "諦めない心", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'コンディション', pos: ["DMF"] },
  { id: 'k137', char: 'isagi', title: "空間認識能力の萌芽", rar: '3', flow: false, pwc: "2", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k138', char: 'kira', title: "みんなに届ける恩返し", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'スタミナ', pos: ["LSB"] },
  { id: 'k139', char: 'kira', title: "松風黒王のエース", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k140', char: 'nagi', title: "異次元の発想", rar: '3', flow: false, pwc: "2", origin: 'pwc', type: 'テクニック', pos: ["RMF"] },
  { id: 'k141', char: 'niko', title: "影の支配者", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k142', char: 'niko', title: "無限の発想", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: '賢さ', pos: ["LMF"] },
  { id: 'k143', char: 'raichi', title: "起死回生の一蹴", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["RSB"] },
  { id: 'k144', char: 'raichi', title: "執念の男", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'スタミナ', pos: ["CB"] },
  { id: 'k145', char: 'raichi', title: "傍若無人強奪", rar: '3', flow: false, pwc: "3", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k146', char: 'reo', title: "御曹司", rar: '3', flow: false, pwc: "2", origin: 'pwc', type: '賢さ', pos: ["RMF"] },
  { id: 'k147', char: 'tokimitsu', title: "新BLランキング3位", rar: '3', flow: false, pwc: "2", origin: 'pwc', type: 'スタミナ', pos: ["DMF"] },
  { id: 'k148', char: 'zantetsu', title: "独特な語彙力", rar: '3', flow: false, pwc: "2", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k149', char: 'bachira', title: "ドリブラー", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k150', char: 'chigiri', title: "スピードスター", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'スピード', pos: ["LWG"] },
  { id: 'k151', char: 'gagamaru', title: "肉体のバネ", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'フィジカル', pos: ["RSB"] },
  { id: 'k152', char: 'iemon', title: "鉄壁", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'コンディション', pos: ["DMF"] },
  { id: 'k153', char: 'igarashi', title: "南無三", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'コンディション', pos: ["RWG"] },
  { id: 'k154', char: 'imamura', title: "恋愛脳", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'テクニック', pos: ["DMF"] },
  { id: 'k155', char: 'kira', title: "日本サッカー界の宝", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k156', char: 'kunigami', title: "スーパーヒーローの卵", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'キック', pos: ["CF"] },
  { id: 'k157', char: 'kuon', title: "ハイジャンパー", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k158', char: 'naruhaya', title: "ムードメーカー", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: '賢さ', pos: ["RSB"] },
  { id: 'k159', char: 'niko', title: "チームＹの心臓", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: '賢さ', pos: ["LMF"] },
  { id: 'k160', char: 'okawa', title: "熊本県大会得点王", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'コンディション', pos: ["CF"] },
  { id: 'k161', char: 'raichi', title: "スタミナの塊", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'スタミナ', pos: ["RWG"] },
  { id: 'k162', char: 'wanima_j', title: "弟との以心伝心連携", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'キック', pos: ["LWG"] },
  { id: 'k163', char: 'wanima_k', title: "兄との以心伝心連携", rar: '2', flow: false, pwc: "2", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k164', char: 'bachira', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k165', char: 'chigiri', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'スピード', pos: ["RWG"] },
  { id: 'k166', char: 'gagamaru', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k167', char: 'iemon', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'コンディション', pos: ["LWG"] },
  { id: 'k168', char: 'igarashi', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'コンディション', pos: ["LWG"] },
  { id: 'k169', char: 'imamura', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'テクニック', pos: ["OMF"] },
  { id: 'k170', char: 'isagi', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'キック', pos: ["OMF"] },
  { id: 'k171', char: 'kira', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'コンディション', pos: ["RMF"] },
  { id: 'k172', char: 'kunigami', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k173', char: 'kuon', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'フィジカル', pos: ["LSB"] },
  { id: 'k174', char: 'naruhaya', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'スピード', pos: ["RMF"] },
  { id: 'k175', char: 'niko', title: "チームＹ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: '賢さ', pos: ["LSB"] },
  { id: 'k176', char: 'okawa', title: "チームＹ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'フィジカル', pos: ["CB"] },
  { id: 'k177', char: 'raichi', title: "チームＺ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'スタミナ', pos: ["CF"] },
  { id: 'k178', char: 'wanima_j', title: "チームＷ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: '賢さ', pos: ["LSB"] },
  { id: 'k179', char: 'wanima_k', title: "チームＷ", rar: '1', flow: false, pwc: "1", origin: 'pwc', type: 'テクニック', pos: ["LMF"] }
  ];
})(typeof globalThis !== 'undefined' ? globalThis : this);
